import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'

import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { cn } from '@/lib/utils'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bambang MIS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen w-full bg-background font-sans text-base antialiased',
          'flex flex-col',
          'overflow-x-hidden',
          'text-foreground',
          'leading-normal',
          inter.className,
        )}
      >
        <main>{children}</main>
        <Toaster
          toastOptions={{
            classNames: {
              toast:
                'group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg group-[.toaster]:pointer-events-auto',
            },
          }}
        />
      </body>
    </html>
  )
}
